### PR TITLE
group6_abstract.rnw

### PR DESCRIPTION
**Pull request by jvanthonygit**

### CODE REVIEW

**Comment by bdetweiler** [comment]
Did you mean to close this?

**Comment by jvanthonygit** [comment]
No I should not have I am sorry

**Review by bdetweiler — COMMENTED** [review]
This is kind of a disclaimer. Do we need it in the abstract? Maybe we can phrase one of the other statements to mention this limitation.

**Comment by jvanthonygit** [comment]
That's fine with me.

**Pull request merged**
